<!DOCTYPE html>
<html>

	<head>
		<meta charset="utf-8">
		<title>
			<?php echo $page_title;?>
		</title>
		<style type="text/css">
			body {
				background: url(../img/signup.jpg);
				font-family: 'Microsoft Yahei', '微软雅黑', arial, 'Hiragino Sans GB', '宋体', Tahoma, Arial, Helvetica, STHeiti;
			}
			div {
				height: 400px;
				width: 800px;
				background: rgba(180, 180, 180, .8);
				border-radius: 5px;
				box-shadow: 3px 3px 5px #333;
				margin: 100px auto;
			}
			h2 {
				margin-left: 50px;
				margin-right: 50px;
				padding-top: 30px;
				padding-bottom: 30px;
			}
			p {
				margin-left: 64px;
				margin-right: 64px;
				padding-top: 50px;
				padding-bottom: 50px;
				font-size: 18px;
				text-align: center;
			}
			a{
				text-decoration: none;
			}
		</style>
	</head>

	<body>
		<div>
			<h2>请注意:</h2>
			<!--此段应在引用后加一对p和内容并封闭div-->
<p>
